# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
Item.destroy_all
UserItem.destroy_all

m = User.create(first: "Matthew", last:"Kay",username: "matthew_kay")
h = User.create(first: "Heloise", last:"Taillet", username: "heloise_taillet")
y = User.create(first: "Yolanda", last:"Flatiron",username: "yolanda_flatiron")
n = User.create(first: "Hai", last:"Nguyen", username: "hai_nguyen")
r = User.create(first: "Ross", last:"theBoss", username: "ross_theboss")
ping = User.create(first: "Ping", last:"Pong", username: "ping_pong")
serven = User.create(first: "Serven", last:"Maraghi", username: "serven_maraghi")
a = User.create(first: "Anthony", last:"Gregg", username: "anthony_gregg")
sharon = User.create(first: "Sharon", last:"Naborf", username: "sharon_naborf")

i1 = Item.create(name: "Cetaphil Gentle Skin Cleanser", price: "9.52", keywords: "normalskin combo acne oilyskin", image: "https://ship.kroger.com/img/Products/500/Cetaphil/Cetaphil-Gentle-Skin-Cleanser-302993921080.jpg")
i2 = Item.create(name: "Dove Cucumber Body Wash", price: "8.99", keywords: "normalskin", image:  'https://i5.walmartimages.com/asr/b82d3127-642a-4837-9a16-2f228630b0da_1.9786ba16e490da0b8862964dd81f42b6.jpeg?odnWidth=undefined&odnHeight=undefined&odnBg=ffffff')
i3 = Item.create(name: "Nexxus Volumizing Shampoo", price: "11.99", keywords: "dryhair flat", image: 'https://images-na.ssl-images-amazon.com/images/I/71A2MHgKXqL._SY355_.jpg')
i4 = Item.create(name: "Nexxus Volumizing Condition", price: "11.99", keywords: "dryhair flat", image: 'https://images-na.ssl-images-amazon.com/images/I/71A2MHgKXqL._SY355_.jpg')
i5 = Item.create(name: "Dr. Bronner's Peppermint Pure-Castile Liquid Soap", price: "12.59", keywords: "dryskin sensitive", image: "https://images-na.ssl-images-amazon.com/images/I/81qq7ET4ZOL._SY355_.jpg")
i6 = Item.create(name: "Sensodyne ProNamel Toothpaste", price: "4.89", image: "https://target.scene7.com/is/image/Target/GUEST_7fd8688c-8db7-49db-abdd-47981455efbf?wid=488&hei=488&fmt=pjpeg")
i7 = Item.create(name: "CeraVe PM Lightweight Facial Moisturizing Lotion", price: "12.39", keywords: "dryskin sensitive", image: "https://target.scene7.com/is/image/Target/GUEST_2195234d-a9c0-43c2-afcb-77990fe36784?wid=488&hei=488&fmt=pjpeg")
i8 = Item.create(name: "Men's Black+White Antiperspirant Deodorant", price: "4.19", image: "https://images-na.ssl-images-amazon.com/images/I/81qLTSrwLsL._SY355_.jpg")
i9 = Item.create(name: "It's a 10 Miracle Leave-in Product", price: "9.59", keywords: "dryhair damaged", image: "https://cdn.shopify.com/s/files/1/1737/7579/products/Miracle_Leave_In_10oz.png?v=1548105876")
i10 = Item.create(name: "Hask Argan Oil Repairing Shampoo", price: "8.99", keywords: "dryhair damaged", image: "https://images.ulta.com/is/image/Ulta/2541382?$detail$")
i11 = Item.create(name: "Tresemme Total Repair Conditioner", price: "3.99", keywords: "dryhair damaged", image:"https://target.scene7.com/is/image/Target/GUEST_feeb66a3-f358-4234-a377-a83e4c618be2?wid=488&hei=488&fmt=pjpeg")
i12 = Item.create(name: "Colgate", price: "2.39", image: "https://www.multivu.com/players/English/8477251-colgate-luke-wilson-big-game-tv-commercial/image/NewColgate_1548368703848-HR.jpg")
i13 = Item.create(name: "The Body Shop Body Butter", price: "12.90", keywords: "dryskin sensitive", image: "https://images.ulta.com/is/image/Ulta/2243406")
i14 = Item.create(name: "CVS Benzoyl Peroxide", price: "3.49", keywords: "acne oilyskin", image: "https://www.cvs.com/bizcontent/merchandising/productimages/large/5042811087.jpg")
i15 = Item.create(name: "Dove Men + Care Shampoo", price: "4.49", keywords: "normalhair", image: "https://www.londondrugs.com/on/demandware.static/-/Sites-londondrugs-master/default/dwe16c3a31/products/L4737755/large/L4737755.JPG")
i16 = Item.create(name: "Dove Men + Care Conditioner", price: "4.49", keywords: "normalhair", image:"https://www.londondrugs.com/on/demandware.static/-/Sites-londondrugs-master/default/dwe16c3a31/products/L4737755/large/L4737755.JPG")
i17 = Item.create(name: "Dove Men + Care Body Wash", price: "3.99", keywords: "normalskin", image: "https://www.dollargeneral.com/media/catalog/product/cache/image/700x700/e9c3970ab036de70892d86c6d221abfe/1/2/1266510112665101_dove_men_care_body_and_face_wash_clean_comfort_13.5_oz_main.jpg")
i18 = Item.create(name: "Kiehl's Face Wash", price: "20.00", keywords: "combo", image: "https://www.kiehls.com/dw/image/v2/AANG_PRD/on/demandware.static/-/Sites-kiehls-master-catalog/default/dw5e6e3cdb/Kiehls_ECOMM_2000/SKIN_CARE/Cleansers_Scrubs_and_Masques/Ultra_Facial_Cleanser/Ultra_Facial_Cleanser_3605970024192_5.0fl.oz..jpg?sw=465&sh=390&sm=fit&q=70")
i19 = Item.create(name: "Crest", price: "2.99", image:"https://4044e4d9bb28f4ab5984-baf8685aca841b756e5db60ffa6ae05f.ssl.cf2.rackcdn.com/product_images/n/015/1237155_9__12530_zoom.png")
i20 = Item.create(name: "Aveeno Moisturizer", price: "7.99", keywords: "combo", image:"https://images.ulta.com/is/image/Ulta/2078389")
i21 = Item.create(name: "Clearasil", price: "7.95", keywords: "combo", image:"https://cdn.shopify.com/s/files/1/0115/9600/5434/products/resizelotion_1080x.jpg?v=1533139327")
i22 = Item.create(name: "Axe", price: "2.50", image:"https://images-na.ssl-images-amazon.com/images/I/81ciFYVrsUL._SY355_.jpg")
i23 = Item.create(name: "Arm + Hammer Complete Care", price: "3.10", image:"https://i5.walmartimages.com/asr/8f67e35f-eb25-406c-aeb1-6268ec17739d_1.8dd3f783792fdb590322554886fb0753.jpeg?odnHeight=450&odnWidth=450&odnBg=FFFFFF")
i24 = Item.create(name: "Dove Men + Care Deodorant", price: "4.39", image:"https://target.scene7.com/is/image/Target/GUEST_35faa9f5-9922-42c3-b6b0-155154862322?wid=488&hei=488&fmt=pjpeg")
i25 = Item.create(name: "Avalon Shampoo", price: "11.99", keywords: "normalhair", image:"https://images-na.ssl-images-amazon.com/images/I/71hR8fSNf2L._SY355_.jpg")
i26 = Item.create(name: "Avalon Conditioner", price: "11.99", keywords: "normalhair", image:"https://images-na.ssl-images-amazon.com/images/I/71s5MMlsRuL._SY355_.jpg")
i27 = Item.create(name: "Everyone Soap", price: "10.99", keywords: "normalskin", image: "https://m.media-amazon.com/images/S/aplus-media/vc/594e62c2-fdbb-4ba4-8072-d2ccb40c1441._CR138,0,825,1100_PT0_SX300__.jpg")
i28 = Item.create(name: "Tom's of Maine Antiplaque & Whitening Toothpaste", price: "5.69", image: "https://images-na.ssl-images-amazon.com/images/I/71SC2F52djL._SX355_.jpg")
i29 = Item.create(name: "Tresemme Luxurious Moisture Shampoo", price: "3.99", keywords: "straight thick normalhair", image:"https://images-na.ssl-images-amazon.com/images/I/71UfMD9SKiL._SL1500_.jpg")
i30 = Item.create(name: "Tresemme Luxurious Moisture Conditioner", price: "3.99", keywords: "straight thick normalhair",image:"https://images-na.ssl-images-amazon.com/images/I/71UfMD9SKiL._SL1500_.jpg")
i31 = Item.create(name: "Dove Deep Moisture Body Wash", price: "8.99", keywords: "normalskin", image:"https://i5.walmartimages.com/asr/4331270d-3026-4b7f-9b7e-b52c86512ceb_1.e47e84d350816a868983a19ce0d40c97.jpeg")
i32 = Item.create(name: "Crew Fiber Hair Gel", price: "8.99", keywords: "straight thick normalhair", image:"https://images-na.ssl-images-amazon.com/images/I/51mYHEUJgFL._SY355_.jpg")
i33 = Item.create(name: "Dove Extra Fresh Deodorant", price: "4.39", image: "https://images-na.ssl-images-amazon.com/images/I/81hfR6l0gkL._SY355_.jpg")
i34 = Item.create(name: "Organix Coconut Milk Shampoo", price: "7.99", keywords: "straight thick normalhair", image: "https://images-na.ssl-images-amazon.com/images/I/716wZzvlAwL._SX355_.jpg")
i35 = Item.create(name: "Organix Coconut Milk Conditioner", price: "7.99", keywords: "straight thick normalhair", image: "https://images-na.ssl-images-amazon.com/images/I/716wZzvlAwL._SX355_.jpg")
i36 = Item.create(name: "Clarins Body Wash", price: "18.99", keywords: "dryskin", image:"https://www.clarinsusa.com/on/demandware.static/-/Sites-clarins-master-products/default/dw337fb819/original/Tonic-Bath-Shower-Concentrate-C020101004%20.jpg")
i37 = Item.create(name: "Simple Face Wash Foam", price: "5.59", keywords: "sensitive", image: "http://kontrolmag.com/wp-content/uploads/2017/07/Simple-foam-cleanser.png")
i38 = Item.create(name: "Erborian BB Cream", price: "39.00", keywords: "sensitive", image:"https://img.erborian.com/P.aspx?l=en-GB&s=600&e=jpg&name=erborian-bb-cream-bb-creme-nude-spf-20-erborian-uk&id=6AA30067&v=1")
i39 = Item.create(name: "Head and Shoulders Shampoo", price: "5.99", keywords: "thick normalhair", image:"https://target.scene7.com/is/image/Target/GUEST_4fac745c-f3d9-45e4-8c7c-0631d4836ef8?wid=488&hei=488&fmt=pjpeg")
i40 = Item.create(name: "Head and Shoulders Conditioner", price: "5.99", keywords: "thick normalhair", image:"https://target.scene7.com/is/image/Target/GUEST_4fac745c-f3d9-45e4-8c7c-0631d4836ef8?wid=488&hei=488&fmt=pjpeg")
i41 = Item.create(name: "Dove Cool Moisture Body Wash", price: "9.89", keywords: "normalskin", image:"https://images-na.ssl-images-amazon.com/images/I/71PFcEwOEcL._SY355_.jpg")
i42 = Item.create(name: "Colgate 2-in-1 Whitening Toothpaste Gel & Mouthwash", price: "3.49", image:"https://pics.drugstore.com/prodimg/57484/900.jpg")
i43 = Item.create(name: "Vaseline Men Body and Face Lotion", price: "5.59", image:"https://media3.webcollage.net/ac79cdf3364aac5991e990b9a0382c9b4bf3e3d4?response-content-type=image%2Fjpeg&AWSAccessKeyId=AKIAIIE5CHZ4PRWSLYKQ&Expires=1893487822&Signature=GAHvcXaiNpv6eaoqHFFVHIUYFN0%3D")
i44 = Item.create(name: "Origin Checks & Balances", price: "23.50", keywords: "normalskin", image:"https://images-na.ssl-images-amazon.com/images/I/619Gy93ItlL._SY355_.jpg")
i45 = Item.create(name: "Mario Badescu Oil-Free Moisturizer", price: "20.00", keywords: "normalskin", image:"https://images.bloomingdalesassets.com/is/image/BLM/products/3/optimized/9573633_fpx.tif?op_sharpen=1&wid=700&fit=fit,1&$filtersm$")
i46 = Item.create(name: "Vanilla Secret Deodorant", price: "4.99",image:"https://i5.walmartimages.com/asr/6b10fbca-78a8-4ca1-9d19-078b69e3e454_1.02682f656bcb67579053dcb34868140d.jpeg")


UserItem.create(user:sharon,item:i34, review: "im in luv w the coco")
UserItem.create(user:sharon,item:i35, review: "great conditioner")
UserItem.create(user:sharon,item:i44, review: "nice!")
UserItem.create(user:sharon,item:i45, review: "amazing")
UserItem.create(user:sharon,item:i46, review: "smells like vanilla")
UserItem.create(user:a,item:i41, review: "so cool")
UserItem.create(user:a,item:i39, review: "knees and toes")
UserItem.create(user:a,item:i40, review: "knees and toes!!")
UserItem.create(user:a,item:i42, review: "two in one! woot")
UserItem.create(user:a,item:i43, review: "great stuff")
UserItem.create(user:serven,item:i33, review: "matt and i use the same deodorant #tWinning")
UserItem.create(user:serven,item:i19, review: "my teeth are v clean")
UserItem.create(user:serven,item:i34, review: "i love coconut")
UserItem.create(user:serven,item:i35, review: "smells amazing")
UserItem.create(user:serven,item:i36, review: "makes my skin soft")
UserItem.create(user:serven,item:i37, review: "love it")
UserItem.create(user:serven,item:i7, review: "doctor recommended!")
UserItem.create(user:serven,item:i38, review: "my holy grail")
UserItem.create(user:m,item:i33, review: "so fresh")
UserItem.create(user:m,item:i1, review: "i love it")
UserItem.create(user:m,item:i19, review: "wow")
UserItem.create(user:m,item:i29, review: "it's amazing")
UserItem.create(user:m,item:i30, review: "even better than the shampoo")
UserItem.create(user:m,item:i31, review: "very moist")
UserItem.create(user:m,item:i32, review: "my hair is excellent")
UserItem.create(user:ping,item:i25, review: "avalon rox")
UserItem.create(user:ping,item:i26, review: "woot woot 8/10 recommend")
UserItem.create(user:ping,item:i27, review: "wow this is great soap")
UserItem.create(user:ping,item:i28, review: "i love maine and i hate plaque")
UserItem.create(user:r,item:i23, review: "baking soda i like baking soda")
UserItem.create(user:r,item:i15, review: "i use this because hai uses it")
UserItem.create(user:r,item:i16, review: "me and hai both use this")
UserItem.create(user:r,item:i17, review: "i'm just as clean as hai is")
UserItem.create(user:n,item:i15, review: "i like it")
UserItem.create(user:n,item:i16, review: "it's nice")
UserItem.create(user:n,item:i17, review: "smells fantastic")
UserItem.create(user:n,item:i18, review: "makes my face soft")
UserItem.create(user:n,item:i19, review: "wow")
UserItem.create(user:n,item:i20, review: "amazing")
UserItem.create(user:n,item:i21, review: "great for spot treatment")
UserItem.create(user:n,item:i22, review: "strong smell")
UserItem.create(user:h,item:i1, review: "very gentle")
UserItem.create(user:h,item:i3, review: "great shampoo. smells nice.")
UserItem.create(user:h,item:i4, review: "best conditioner for flat hair")
UserItem.create(user:h,item:i5, review: "this soap literally tingles. not usually a fan of mint but this is awesome")
UserItem.create(user:h,item:i6, review: "fine")
UserItem.create(user:h,item:i7, review: "this is the most light-weight moisturizer ive ever used")
UserItem.create(user:h,item:i8, review: "yes, i use men's deodorant")
UserItem.create(user:h,item:i9, review: "protects your hair")
UserItem.create(user:y,item:i9, review: "love this stuff")
UserItem.create(user:y,item:i10, review: "great for my damaged hair")
UserItem.create(user:y,item:i2, review: "smells nice")
UserItem.create(user:y,item:i11, review: "this is awesome")
UserItem.create(user:y,item:i12, review: "minty")
UserItem.create(user:y,item:i13, review: "i love the body shop. great moisturizer")
UserItem.create(user:y,item:i14, review: "i use this at night")
